datasource:
  master:
    xa-properties:
      url: jdbc:mysql://localhost:3306/demo?useSSL=false
      user: demo
      password: 123456
    xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource

  slave:
    xa-properties:
      # ORACLE必须使用
      URL: jdbc:oracle:thin:@localhost:1521/XE
      user: demo
      password: 123456
    xa-data-source-class-name: oracle.jdbc.xa.client.OracleXADataSource

spring:
  jta:
    enabled: true
