server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: select "1"
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    wang.seamas.mapper: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/**/*Mapper.xml