datasource:
  master:
    jdbc-url: jdbc:mysql://localhost:3306/demo?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
  slave:
    jdbc-url: jdbc:oracle:thin:@localhost:1521/XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: demo
    password: 123456
logging:
  level:
    wang.seamas.mapper.*: debug
