datasource:
  master:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
  slave:
    url: jdbc:mysql://localhost:3306/slave?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: 123456
